#cloud-config
package_update: false
hostname: ${hostname}
write_files:
  - path: /etc/systemd/system/walinuxagent.service
    content: |
      [Unit]
      Description=Azure Linux Agent
      After=network.target

      [Service]
      ExecStart=/usr/sbin/waagent -daemon
      Restart=always

      [Install]
      WantedBy=multi-user.target
    owner: root:root
    permissions: '0644'

runcmd:
  # Download and install the Kali archive keyring if missing
  - wget https://archive.kali.org/archive-keyring.gpg -O /usr/share/keyrings/kali-archive-keyring.gpg
  
  # Connect to temporary Debian repo
  - echo "deb http://deb.debian.org/debian bookworm main" | sudo tee /etc/apt/sources.list.d/debian-temp.list
  - 'echo "Package: xautolock" >> /etc/apt/preferences.d/pin-xautolock'
  - 'echo "Pin: release a=bookworm" >> /etc/apt/preferences.d/pin-xautolock'
  - 'echo "Pin-Priority: 990" >> /etc/apt/preferences.d/pin-xautolock'

  # Update package list
  - sudo apt-get update
  
  # Install xautolock
  - sudo apt-get install -y xautolock
  
  # Add xautolock config to /etc/profile
  - echo -e '\nif [ -n "$DISPLAY" ]; then\n    xautolock -time 3 -locker "sudo /sbin/shutdown now" &\nfi' | sudo tee -a /etc/profile > /dev/null
  
  # Add TMOUT Variable to /et/profile
  - echo "TMOUT=1200" >> /etc/profile
  
  # Add auto shutdown script for shell sessions
  - echo -e '#!/bin/bash\nnum_users=$(who | cut -d " " -f 1 | wc -l)\nif [ "$num_users" -eq 0 ]; then\n  /bin/systemctl poweroff --now\nfi' > /etc/cron.hourly/shutdown_if_idle && chmod +x /etc/cron.hourly/shutdown_if_idle

  # Set hostname
  - echo ${hostname} | sudo tee /etc/hostname
  - sudo sed -i '/^127\.0\.1\.1/c\127.0.1.1\t${hostname}' /etc/hosts

  # Install alternate DHCP client
  - apt-get install -y isc-dhcp-client
  - apt-get purge -y dhcpcd-base
  - systemctl stop dhcpcd-base || true
  - echo -e "auto eth0\niface eth0 inet dhcp" > /etc/network/interfaces.d/eth0.cfg
  - systemctl restart networking

  # Install Azure Linux Agent
  - apt install python3-pip python3-setuptools python3-wheel
  - git clone https://github.com/Azure/WALinuxAgent.git
  - cd WALinuxAgent
  - python3 setup.py install
  - systemctl daemon-reexec
  - systemctl daemon-reload
  - systemctl enable --now walinuxagent
  - systemctl start walinuxagent

  # Install GUIs and remote access servers
  - DEBIAN_FRONTEND=noninteractive apt-get install -y kali-desktop-xfce lxde openbox obconf xrdp x2goserver x2goserver-xsession apache2 wireshark nmap python2 snort hping3 iproute2

  # Install Zenmap
  - wget https://nmap.org/dist/zenmap-7.93-1.noarch.rpm
  - apt-get install alien
  - alien zenmap-7.93-1.noarch.rpm
  - sudo dpkg -i zenmap_7.93-2_all.deb

  # Enable and start XRDP
  - systemctl enable --now xrdp xrdp-sesman

  # Set up default session GUI
  - echo "startlxde" > /home/ita/.xsession
  - chmod +x /home/ita/.xsession
  - chown ita:ita /home/ita/.xsession
