#cloud-config
package_update: false
hostname: ${hostname}

runcmd:
  # Download and install the Kali archive keyring if missing
  - wget https://archive.kali.org/archive-keyring.gpg -O /usr/share/keyrings/kali-archive-keyring.gpg

  # Update package lists
  - apt-get update

  # Install GUIs and remote access servers
  - DEBIAN_FRONTEND=noninteractive apt-get install -y kali-desktop-xfce lxde openbox obconf xrdp x2goserver x2goserver-xsession apache2 wireshark nmap python2 snort hping3

  # Install Zenmap
  - wget https://nmap.org/dist/zenmap-7.93-1.noarch.rpm
  - apt-get install alien
  - alien zenmap-7.93-1.noarch.rpm
  - sudo dpkg -i zenmap_7.93-2_all.deb

  # Enable and start XRDP
  - systemctl enable --now xrdp xrdp-sesman

  # Set up default session GUI
  - echo "startlxde" > /home/ita/.xsession
  - chmod +x /home/ita/.xsession
  - chown ita:ita /home/ita/.xsession
  
# Install alternate DHCP client
  #- apt-get install -y isc-dhcp-client
  #- apt-get purge -y dhcpcd5
  #- systemctl stop dhcpcd || true
  #- systemctl disable dhcpcd || true
  #- echo -e "auto eth0\niface eth0 inet dhcp" > /etc/network/interfaces.d/eth0.cfg
  #- systemctl restart networking
