#cloud-config
package_update: true
write_files:
  - path: /etc/apt/sources.list.d/kali.list
    content: |
      deb http://http.kali.org/kali kali-rolling main contrib non-free
runcmd:
  # Install Kali XFCE desktop and XRDP
  - apt-get install -y kali-archive-keyring
  - apt-get install -y kali-desktop-xfce xrdp

  # Enable and start XRDP
  - systemctl enable --now xrdp xrdp-sesman

  # Setup XFCE session for login
  - echo "startxfce4" > /home/kali/.xsession
  - chmod +x /home/kali/.xsession
  - chown kali:kali /home/kali/.xsession

  # Restart XRDP to finalize setup
  - systemctl restart xrdp
