#cloud-config
package_update: true
bootcmd:
 - [ cloud-init-per, once, wait-network, sh, -c, "while ! ping -c1 archive.ubuntu.com; do sleep 1; done" ]
runcmd:
  # Download and install the Kali archive keyring if missing
  - wget https://archive.kali.org/archive-keyring.gpg -O /usr/share/keyrings/kali-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/kali-archive-keyring.gpg] http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list.d/kali.list

  # Update package lists
  - apt-get update

  # Install Kali XFCE desktop and XRDP
  - apt-get install -y kali-archive-keyring
  - apt-get install -y kali-desktop-xfce xrdp

  # Enable and start XRDP
  - systemctl enable --now xrdp xrdp-sesman

  # Setup XFCE session for login
  - echo "startxfce4" > /home/kali/.xsession
  - chmod +x /home/kali/.xsession
  - chown kali:kali /home/kali/.xsession

  # Restart XRDP to finalize setup
  - systemctl restart xrdp
