#cloud-config
package_update: false

runcmd:
  # Download and install the Kali archive keyring if missing
  - wget https://archive.kali.org/archive-keyring.gpg -O /usr/share/keyrings/kali-archive-keyring.gpg

  # Update package lists
  - apt-get update

  # Install Kali XFCE desktop and XRDP
  - DEBIAN_FRONTEND=noninteractive apt-get install -y kali-desktop-xfce xrdp

  # Enable and start XRDP
  - systemctl enable --now xrdp xrdp-sesman

  # Setup XFCE session for login
  - echo "startxfce4" > /home/kali/.xsession
  - chmod +x /home/kali/.xsession
  - chown kali:kali /home/kali/.xsession

  # Restart XRDP to finalize setup
  - systemctl restart xrdp
