#cloud-config
package_update: false
hostname: ${hostname}

runcmd:
  # Download and install the Kali archive keyring if missing
  - wget https://archive.kali.org/archive-keyring.gpg -O /usr/share/keyrings/kali-archive-keyring.gpg

  # Update package lists
  - apt-get update

  # Install GUIs and remote access servers
  - DEBIAN_FRONTEND=noninteractive apt-get install -y kali-desktop-xfce lxde openbox obconf xrdp x2goserver x2goserver-xsession

  # Enable and start XRDP
  - systemctl enable --now xrdp xrdp-sesman

  # Set up default session GUI
  - echo "startlxde" > /home/ita/.xsession
  - chmod +x /home/ita/.xsession
  - chown ita:ita /home/ita/.xsession
